version: "3.7"
services:
  vb_sogl:
    build: .
    ports:
      - 14234:80
    working_dir: /app
    volumes:
      - ./:/app
    logging:
      options:
        max-size: "1m"
        max-file: "3"
