"""add list info columns

Revision ID: 08f3d63430fb
Revises: 162a8f731065
Create Date: 2024-03-17 21:30:53.108026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f3d63430fb'
down_revision = '162a8f731065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_process', sa.Column('list_info1', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('list_info2', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('list_info3', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('list_info4', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('list_info5', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('list_info6', sa.String(), nullable=True))
    op.add_column('business_process', sa.Column('tasks_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_process', 'tasks_info')
    op.drop_column('business_process', 'list_info6')
    op.drop_column('business_process', 'list_info5')
    op.drop_column('business_process', 'list_info4')
    op.drop_column('business_process', 'list_info3')
    op.drop_column('business_process', 'list_info2')
    op.drop_column('business_process', 'list_info1')
    # ### end Alembic commands ###
