"""add bp_uuid

Revision ID: 0b565b5c219b
Revises: 
Create Date: 2023-02-21 15:17:13.247911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b565b5c219b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_process',
    sa.Column('bp_uuid', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('bp_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bp_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bp_uuid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('full_user_name', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('file_attachment',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bp_uuid', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_ext', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bp_uuid'], ['business_process.bp_uuid'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_file_attachment_bp_uuid'), 'file_attachment', ['bp_uuid'], unique=False)
    op.create_table('soglasovanie_task',
    sa.Column('task_id', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('bp_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('verdict_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bp_uuid'], ['business_process.bp_uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_soglasovanie_task_bp_uuid'), 'soglasovanie_task', ['bp_uuid'], unique=False)
    op.create_index(op.f('ix_soglasovanie_task_user_id'), 'soglasovanie_task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soglasovanie_task_user_id'), table_name='soglasovanie_task')
    op.drop_index(op.f('ix_soglasovanie_task_bp_uuid'), table_name='soglasovanie_task')
    op.drop_table('soglasovanie_task')
    op.drop_index(op.f('ix_file_attachment_bp_uuid'), table_name='file_attachment')
    op.drop_table('file_attachment')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('business_process')
    # ### end Alembic commands ###
