"""empty message

Revision ID: 3ea8ef3e06d8
Revises: a9da6e374f47
Create Date: 2020-06-26 12:36:15.147985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea8ef3e06d8'
down_revision = 'a9da6e374f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_attachment',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bp_id', sa.String(length=20), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bp_id'], ['business_process.bp_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_file_attachment_bp_id'), 'file_attachment', ['bp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_attachment_bp_id'), table_name='file_attachment')
    op.drop_table('file_attachment')
    # ### end Alembic commands ###
