"""init db

Revision ID: 518f31b37686
Revises: 
Create Date: 2020-05-12 13:07:08.755089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518f31b37686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soglasovanie_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bp_id', sa.String(), nullable=False),
    sa.Column('bp_description', sa.String(), nullable=False),
    sa.Column('bp_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('date_of_action', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soglasovanie_task')
    # ### end Alembic commands ###
