"""empty message

Revision ID: 7e5f32f446aa
Revises: 
Create Date: 2020-06-01 11:33:04.446296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5f32f446aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_process',
    sa.Column('bp_id', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bp_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bp_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('soglasovanie_task',
    sa.Column('task_id', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('bp_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('verdict_date', sa.DateTime(), nullable=True),
    sa.Column('verdict_send_to_1c', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bp_id'], ['business_process.bp_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_soglasovanie_task_bp_id'), 'soglasovanie_task', ['bp_id'], unique=False)
    op.create_index(op.f('ix_soglasovanie_task_user_id'), 'soglasovanie_task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soglasovanie_task_user_id'), table_name='soglasovanie_task')
    op.drop_index(op.f('ix_soglasovanie_task_bp_id'), table_name='soglasovanie_task')
    op.drop_table('soglasovanie_task')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('business_process')
    # ### end Alembic commands ###
