"""empty message

Revision ID: 9bcbfcd99017
Revises: 3ea8ef3e06d8
Create Date: 2020-06-30 10:25:25.938835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcbfcd99017'
down_revision = '3ea8ef3e06d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_attachment', sa.Column('file_ext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_attachment', 'file_ext')
    # ### end Alembic commands ###
