"""empty message

Revision ID: df0e707ba136
Revises: 
Create Date: 2020-05-12 16:07:18.960069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0e707ba136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_process',
    sa.Column('bp_id', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bp_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bp_id')
    )
    op.create_table('soglasovanie_task',
    sa.Column('task_id', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('bp_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('verdict_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bp_id'], ['business_process.bp_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soglasovanie_task')
    op.drop_table('business_process')
    # ### end Alembic commands ###
